### PR TITLE
Speed and documentation

### PR DESCRIPTION
**Pull request by kozakaron**

### CODE REVIEW

**Comment by kozakaron** [comment]
**Speed update:**

The simulations run abou 25-50% faster depending on machine. This was primarily achieved trough less numpy array allocations and some inlining. The ODE function returns bitexactly the same results as before. Some benchmarks:

```
WindowsPC: Windows 11; AMD Ryzen 7 5800H (8*2 cores 3.2-4.4 GHz); 32 GB DDR4 RAM; Python 3.10.11;
LinuxPC: Ubuntu 22; Intel Core i7-3770 CPU (8 cores 3.4-3.9 GHz); 16 GB DDR3 RAM; Python 3.10.12

Ammonia: chem_Otomo2018_without_O; 12 species; 35 reactions; no_excitation; no evaporation;
Hydrogen: chemkin_AR_HE.ipynb; 12 species; 30 reactions; sin_impulse; with evaporation;

There is always 100 s LSODA timeout and 0 s Radau timeout. In case of Ammonia, the slower code (old) resulted in more timeouts than the faster code (new).
In case of Hydrogen, there were no timeouts.


Ammonia + WindowsPC: (400 combinations)
               | single-threaded | multi-threaded | ratio
---------------+-----------------+----------------+------
    new        |  2955.08 [s]    |  374.21 [s]    | 7.90
    old        |  5647.31 [s]    |  551.93 [s]    | 10.23
    ratio      |  0.52           |  0.67          |

Ammonia + LinuxPC: (400 combinations)
               | single-threaded | multi-threaded | ratio
---------------+-----------------+----------------+------
    new        | 7611.26  [s]    |  1456.92 [s]   | 5.23   
    old        | 10790.03 [s]    |  1736.31 [s]   | 6.21    
    ratio      | 0.70            |  0.84          |

Hydrogen + WindowsPC: (500 combinations)
               | single-threaded | multi-threaded | ratio
---------------+-----------------+----------------+------
    new        |  144.67 [s]     |  31.35 [s]     | 4.61 
    old        |  301.35 [s]     |  78.18 [s]     | 3.85
    ratio      |  0.48           |  0.40          |

Hydrogen + LinuxPC: (500 combinations)
               | single-threaded | multi-threaded | ratio
---------------+-----------------+----------------+------
    new        |  373.10 [s]     |  83.78 [s]     | 4.45 
    old        |  534.59 [s]     |  116.44 [s]    | 4.59
    ratio      |  0.70           |  0.72          |
```

**Comment by kozakaron** [comment]
**Gradient descent step size control**

The step size has a new control method, making it possible for the step size to grow. This improves convergence speed, and reduces the number of settings. 

visualization

**Comment by kozakaron** [comment]
**Name changes**

 * private functions and private global variables (the ones, the user are not meant to use) now start with an underscore (e.g. _private_variable)
 * functions now have a consistent naming (function_name not Function_name, FunctionName or funcname or whatever).
     * Legacy names for vapour_pressure (VapourPressure) and viscosity (Viscosity) are also maintained for backward compatibility (only class names should start with capital letter)
  * energy_efficiency was renamed to energy_demand (it was incorrect naming). data will contain both of them and Read_CSV_files.ipynb can handle when the latter one is missing for backward compatibility
  * example files are renamed (they no longer contain spaces, and start with capital letter. There are no longer two bruteforce param studies)

**Comment by kozakaron** [comment]
**Density as cpar**

rho_L is introduced as control parameter. It has a default value (backward compatible)

**Comment by kozakaron** [comment]
**Extra plots**

Internal and external pressures are displayed on the same plot

There is a simple built in way to modify the ODE function _f() and plot() to display additional dimensions (e.g. the thermal, viscous, acoustic dissipated energy separately) The extra calculations and dimensions will only be used during plotting, param studies wont be slower

image

**Comment by kozakaron** [comment]
**Documentation**

All public and many private functions as well as all python files have in code documentation.

doc_generator.py can generate automatically a markdown file from the incode docs: [link](https://github.com/hihihi2001/Bubble_dynamics_simulation/blob/ammonia_aron_kozak/DOCUMENTATION.md)

README.md was updated, it no longer contains deprecated information

I will soon make a help guide to set and use the gradient descent based optimization

**Comment by kozakaron** [comment]
**Excitation**

Three new excitation types were added with complex pressure functions.

A new function, excitation.plot_excitation() can be used to plot any excitation.

Excitations now have default values, so example_cpar() will now return a valid capr

image

**Review by mrkf100 — APPROVED** [review]

**Pull request merged**
